version: '3.10'

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: name_news_board_db
            POSTGRES_USER: user_news_board_db
            POSTGRES_PASSWORD: f4mXiEVasjk!asS%%NNN6R@K%S?!fODtJ&TD1k2!0:*pFu!UpTm@3p
        volumes:
            - ./pgdb:/var/lib/postgresql/data

    redis:
        image: redis
        ports:
            - '127.0.0.1:6379:6379'
        restart: always
